# Generated by Django 2.0.3 on 2019-12-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airquality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('qualityLevel', models.CharField(max_length=4, verbose_name='质量等级')),
                ('AQI', models.IntegerField(max_length=4, verbose_name='AQI')),
                ('PM25', models.IntegerField(max_length=4, verbose_name='PM2.5')),
                ('PM10', models.IntegerField(max_length=4, verbose_name='PM10')),
                ('SO2', models.IntegerField(max_length=4, verbose_name='SO2')),
                ('NO2', models.IntegerField(max_length=4, verbose_name='NO2')),
                ('CO', models.CharField(max_length=6, verbose_name='CO')),
                ('O3', models.IntegerField(max_length=4, verbose_name='O3')),
            ],
            options={
                'verbose_name': '空气质量管理',
                'verbose_name_plural': '空气质量管理',
            },
        ),
    ]
